// Code generated by protoc-gen-go.
// source: clarifystatussvc.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	clarifystatussvc.proto

It has these top-level messages:
	HostStatusRequest
	HostStatusReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HostStatusReply_Host_HostStatus int32

const (
	HostStatusReply_Host_STOPPED     HostStatusReply_Host_HostStatus = 0
	HostStatusReply_Host_PENDING     HostStatusReply_Host_HostStatus = 1
	HostStatusReply_Host_MIXED       HostStatusReply_Host_HostStatus = 2
	HostStatusReply_Host_STARTED     HostStatusReply_Host_HostStatus = 3
	HostStatusReply_Host_UNALLOCATED HostStatusReply_Host_HostStatus = 4
)

var HostStatusReply_Host_HostStatus_name = map[int32]string{
	0: "STOPPED",
	1: "PENDING",
	2: "MIXED",
	3: "STARTED",
	4: "UNALLOCATED",
}
var HostStatusReply_Host_HostStatus_value = map[string]int32{
	"STOPPED":     0,
	"PENDING":     1,
	"MIXED":       2,
	"STARTED":     3,
	"UNALLOCATED": 4,
}

func (x HostStatusReply_Host_HostStatus) String() string {
	return proto.EnumName(HostStatusReply_Host_HostStatus_name, int32(x))
}
func (HostStatusReply_Host_HostStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0, 0}
}

type HostStatusRequest struct {
}

func (m *HostStatusRequest) Reset()                    { *m = HostStatusRequest{} }
func (m *HostStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*HostStatusRequest) ProtoMessage()               {}
func (*HostStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HostStatusReply struct {
	Hosts []*HostStatusReply_Host `protobuf:"bytes,1,rep,name=hosts" json:"hosts,omitempty"`
	Error string                  `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *HostStatusReply) Reset()                    { *m = HostStatusReply{} }
func (m *HostStatusReply) String() string            { return proto.CompactTextString(m) }
func (*HostStatusReply) ProtoMessage()               {}
func (*HostStatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HostStatusReply) GetHosts() []*HostStatusReply_Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *HostStatusReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type HostStatusReply_Host struct {
	Hostname string                          `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Status   HostStatusReply_Host_HostStatus `protobuf:"varint,2,opt,name=status,enum=pb.HostStatusReply_Host_HostStatus" json:"status,omitempty"`
}

func (m *HostStatusReply_Host) Reset()                    { *m = HostStatusReply_Host{} }
func (m *HostStatusReply_Host) String() string            { return proto.CompactTextString(m) }
func (*HostStatusReply_Host) ProtoMessage()               {}
func (*HostStatusReply_Host) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *HostStatusReply_Host) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *HostStatusReply_Host) GetStatus() HostStatusReply_Host_HostStatus {
	if m != nil {
		return m.Status
	}
	return HostStatusReply_Host_STOPPED
}

func init() {
	proto.RegisterType((*HostStatusRequest)(nil), "pb.HostStatusRequest")
	proto.RegisterType((*HostStatusReply)(nil), "pb.HostStatusReply")
	proto.RegisterType((*HostStatusReply_Host)(nil), "pb.HostStatusReply.Host")
	proto.RegisterEnum("pb.HostStatusReply_Host_HostStatus", HostStatusReply_Host_HostStatus_name, HostStatusReply_Host_HostStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ClarifyStatus service

type ClarifyStatusClient interface {
	GetHostStatus(ctx context.Context, in *HostStatusRequest, opts ...grpc.CallOption) (*HostStatusReply, error)
}

type clarifyStatusClient struct {
	cc *grpc.ClientConn
}

func NewClarifyStatusClient(cc *grpc.ClientConn) ClarifyStatusClient {
	return &clarifyStatusClient{cc}
}

func (c *clarifyStatusClient) GetHostStatus(ctx context.Context, in *HostStatusRequest, opts ...grpc.CallOption) (*HostStatusReply, error) {
	out := new(HostStatusReply)
	err := grpc.Invoke(ctx, "/pb.ClarifyStatus/GetHostStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ClarifyStatus service

type ClarifyStatusServer interface {
	GetHostStatus(context.Context, *HostStatusRequest) (*HostStatusReply, error)
}

func RegisterClarifyStatusServer(s *grpc.Server, srv ClarifyStatusServer) {
	s.RegisterService(&_ClarifyStatus_serviceDesc, srv)
}

func _ClarifyStatus_GetHostStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClarifyStatusServer).GetHostStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ClarifyStatus/GetHostStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClarifyStatusServer).GetHostStatus(ctx, req.(*HostStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClarifyStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ClarifyStatus",
	HandlerType: (*ClarifyStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHostStatus",
			Handler:    _ClarifyStatus_GetHostStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clarifystatussvc.proto",
}

func init() { proto.RegisterFile("clarifystatussvc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4e, 0x83, 0x40,
	0x14, 0x85, 0x3b, 0xf4, 0x47, 0x7b, 0x9b, 0x5a, 0x9c, 0xaa, 0x21, 0x5d, 0x55, 0xdc, 0x74, 0x35,
	0x8b, 0xba, 0x32, 0xc6, 0x05, 0x05, 0x52, 0x9b, 0x54, 0x20, 0xb4, 0x26, 0x6e, 0x81, 0x8c, 0xd1,
	0x84, 0x3a, 0x38, 0x33, 0x98, 0xf4, 0x15, 0x7c, 0x1a, 0x1f, 0xd1, 0x30, 0x43, 0x94, 0x34, 0xba,
	0x3c, 0x87, 0xef, 0x72, 0xcf, 0xdc, 0x03, 0x17, 0x59, 0x9e, 0xf0, 0xd7, 0xe7, 0xbd, 0x90, 0x89,
	0x2c, 0x85, 0xf8, 0xc8, 0x48, 0xc1, 0x99, 0x64, 0xd8, 0x28, 0x52, 0x7b, 0x0c, 0xa7, 0xf7, 0x4c,
	0xc8, 0x8d, 0xfa, 0x14, 0xd3, 0xf7, 0x92, 0x0a, 0x69, 0x7f, 0x1a, 0x30, 0x6a, 0xba, 0x45, 0xbe,
	0xc7, 0x04, 0xba, 0x2f, 0x4c, 0x48, 0x61, 0xa1, 0x69, 0x7b, 0x36, 0x98, 0x5b, 0xa4, 0x48, 0xc9,
	0x01, 0xa3, 0x74, 0xac, 0x31, 0x7c, 0x06, 0x5d, 0xca, 0x39, 0xe3, 0x96, 0x31, 0x45, 0xb3, 0x7e,
	0xac, 0xc5, 0xe4, 0x0b, 0x41, 0xa7, 0xa2, 0xf0, 0x04, 0x8e, 0x2b, 0xee, 0x2d, 0xd9, 0x51, 0x0b,
	0x29, 0xe2, 0x47, 0xe3, 0x5b, 0xe8, 0xe9, 0xa8, 0x6a, 0xf6, 0x64, 0x7e, 0xf5, 0xdf, 0xae, 0xa6,
	0x59, 0x8f, 0xd8, 0x21, 0xc0, 0xaf, 0x8b, 0x07, 0x70, 0xb4, 0xd9, 0x86, 0x51, 0xe4, 0x7b, 0x66,
	0xab, 0x12, 0x91, 0x1f, 0x78, 0xab, 0x60, 0x69, 0x22, 0xdc, 0x87, 0xee, 0xc3, 0xea, 0xc9, 0xf7,
	0x4c, 0x43, 0x43, 0x4e, 0xbc, 0xf5, 0x3d, 0xb3, 0x8d, 0x47, 0x30, 0x78, 0x0c, 0x9c, 0xf5, 0x3a,
	0x74, 0x9d, 0xca, 0xe8, 0xcc, 0x03, 0x18, 0xba, 0xfa, 0x7e, 0xf5, 0x3f, 0xef, 0x60, 0xb8, 0xa4,
	0xb2, 0xb1, 0xe4, 0xfc, 0x30, 0x9f, 0xba, 0xe2, 0x64, 0xfc, 0x47, 0x6c, 0xbb, 0xb5, 0xb8, 0x81,
	0xcb, 0x8c, 0xed, 0x48, 0x96, 0x53, 0x46, 0xea, 0x62, 0x48, 0x96, 0x97, 0x42, 0x52, 0xae, 0x9f,
	0x40, 0x8a, 0x74, 0x81, 0x5d, 0xed, 0xe8, 0xd1, 0xa8, 0xaa, 0x2b, 0x42, 0x69, 0x4f, 0xf5, 0x76,
	0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x5d, 0xa2, 0x8f, 0xd1, 0x01, 0x00, 0x00,
}
